/*******************************************************************************
Description: Insert the neighborhoods of the city of Cali into the GEOGRAPHIC_AREA table
Author: Andres Felipe Villamizar Collazos
Date 12-10-2023
@copyright: TechCamp
*******************************************************************************/
  
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Paseo de Los Almendros', 596, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Fepicol', 798, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Yira Castro', 1390, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Lili', 1775, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Gran Limonar - Cataya', 1789, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Parcelaciones Pance', 2296, 22);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Andes B - La Riviera', 597, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Anita - La Selva', 1778, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización San Joaquin', 1796, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Potrero Grande', 2196, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Luís II', 696, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Puente del Comercio', 698, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Pondaje', 1398, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Bosques del Limonar', 1788, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudadela Pasoancho', 1793, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Sultana', 2099, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Pízamos III - Las Dalias', 2195, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Valle Grande', 2198, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Torres de Comfandi', 598, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villa del Prado - El Guabito', 599, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Fonaviemcali', 695, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Calimio', 697, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Ingenio', 1780, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Portales - Nuevo Rey', 1785, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Cañaverales - Los Samanes', 1786, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Limonar', 1787, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Cañaveral', 1992, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudadela del Río', 2197, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Calima', 421, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Planta de Tratamiento', 2199, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Río Lili', 2297, 22);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Lleras Restrepo II Etapa', 1393, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Marroquín III', 1394, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Lagos', 1395, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Laguna del Pondaje', 1397, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Puerta del Sol', 1495, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Mojica', 1598, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Morichal', 1599, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Caney', 1774, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Mayapan - Las Vegas', 1781, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Quintas de Don Simón', 1782, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Prados del Limonar', 1794, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Meléndez', 1896, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Terrón Colorado', 101, 1);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Vista Hermosa', 102, 1);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Rita', 201, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Teresita', 202, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Arboledas', 203, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Normandía', 204, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Juanambú', 205, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Centenario', 206, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Granada', 207, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Versalles', 208, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Vicente', 209, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Mónica ', 210, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Prados del Norte', 211, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Flora', 212, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Campiña', 213, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Paz', 214, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Bosque', 215, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Menga', 216, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad Los Alamos', 217, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Chipichape', 218, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Brisas de los Alamos', 219, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Nacional', 301, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Peñón', 302, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Antonio', 303, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Cayetano', 304, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Libertadores', 305, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Juan Bosco', 306, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Rosa', 307, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Merced', 308, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Pascual', 309, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Calvario', 310, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Pedro', 311, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Nicolas', 312, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Hoyo', 313, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Piloto', 314, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Navarro - La Chanca', 315, 3);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Jorge Isaacs', 401, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santander', 402, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Porvenir', 403, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Delicias', 404, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Manzanares', 405, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Salomia', 406, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Fátima', 407, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sultana - Berlín - San Francisco ', 408, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Popular', 410, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ignacio Rengifo', 411, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Guillermo Valencia', 412, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Isla', 413, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Marco Fidel Suárez', 414, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Evaristo García', 415, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Esmeralda', 416, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Bolivariano', 417, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Olaya Herrera', 418, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Unidad Residencial Bueno Madrid', 419, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Flora Industrial', 420, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Industria de Licores', 423, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Sena', 501, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Andes', 502, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Guayacanes', 503, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Chiminangos Segunda Etapa', 504, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Chiminangos Primera Etapa', 505, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Metropolitano del Norte', 506, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Luis', 601, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Jorge Eliecer Gaitán', 602, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Paso del Comercio', 603, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Alcázares', 604, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Petecuy Primera Etapa', 605, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Petecuy Segunda Etapa', 606, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Rivera Primera Etapa', 607, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Guaduales', 608, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Petecuy Tercera Etapa', 609, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudadela Floralia', 610, 6);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alfonso López P. 1a. Etapa', 701, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alfonso López P. 2a. Etapa', 702, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alfonso López P. 3a. Etapa', 703, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Puerto Nuevo', 704, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Puerto Mallarino', 705, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización El Ángel del Hogar', 706, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Siete de Agosto', 707, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Pinos', 708, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Marino', 709, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Ceibas', 710, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Base Aérea', 711, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Parque de la Caña', 797, 7);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Primitivo Crespo', 801, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Simón Bolívar', 802, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Saavedra Galindo', 803, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Uribe Uribe', 804, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Mónica Popular', 805, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Floresta', 806, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Benjamín Herrera', 807, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Municipal', 808, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Industrial', 809, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Troncal', 810, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Américas', 811, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Atanasio Girardot', 812, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Fe', 813, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Chapinero', 814, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villa Colombia', 815, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'EL Trébol', 816, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Base', 817, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización La Nueva Base', 818, 8);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alameda', 901, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Bretaña', 902, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Junín', 903, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Guayaquil', 904, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Aranjuez', 905, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Manuel María Buenaventura', 906, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Mónica Belalcázar', 907, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Belalcázar', 908, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sucre', 909, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Barrio Obrero', 910, 9);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Dorado', 1001, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Guabal', 1002, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Libertad', 1003, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Elena', 1004, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Acacias', 1005, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santo Domingo', 1006, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Jorge Zawadsky', 1007, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Olímpico', 1008, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Cristóbal Colón', 1009, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Selva', 1010, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Barrio Departamental', 1011, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Pasoancho', 1012, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Panamericano', 1013, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Colseguros Andes', 1014, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Cristobal', 1015, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Granjas', 1016, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Judas Tadeo I Etapa', 1017, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Judas Tadeo II Etapa', 1018, 10);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Carlos', 1101, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Maracaibo', 1102, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Independencia', 1103, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Esperanza', 1104, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Boyacá', 1105, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Jardín', 1106, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Fortaleza', 1107, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Recuerdo', 1108, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Aguablanca', 1109, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Prado', 1110, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, '20 de Julio', 1111, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Prados de Oriente', 1112, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Sauces', 1113, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villa del Sur', 1114, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'José Holguín Garcés', 1115, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'León XIII', 1116, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'José María Córdoba', 1117, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Pedro Claver', 1118, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Conquistadores', 1119, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Gran Colombia', 1120, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Benito', 1121, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Primavera', 1122, 11);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villanueva', 1201, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Asturias', 1202, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Eduardo Santos', 1203, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alfonso Barberena A.', 1204, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Paraiso', 1205, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Fenalco Kennedy', 1206, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Nueva Floresta', 1207, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Julio Rincón', 1208, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Doce de Octubre', 1209, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Rodeo', 1210, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sindical', 1211, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Bello Horizonte', 1212, 12);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ulpiano Lloreda', 1301, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Vergel', 1302, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Poblado I', 1303, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Poblado II', 1304, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Comuneros Segunda Etapa', 1305, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ricardo Balcázar', 1306, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Omar Torrijos', 1307, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Diamante', 1308, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Lleras Restrepo', 1309, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villa del Lago', 1310, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Robles', 1311, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Rodrigo Lara Bonilla', 1312, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Charco Azul', 1313, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villablanca', 1314, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Calipso', 1315, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alfonso Bonilla Aragón', 1401, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alirio Mora Beltrán', 1402, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Manuela Beltrán', 1403, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Las Orquídeas', 1404, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'José Manuel Marroquín Segunda Etapa', 1405, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'José Manuel Marroquín Primera Etapa', 1406, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Retiro', 1501, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Comuneros I', 1502, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Laureano Gómez', 1503, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Vallado', 1504, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Mariano Ramos', 1601, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'República de Israel', 1602, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Unión de Vivienda Popular', 1603, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Antonio Nariño', 1604, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Brisas del Limonar', 1605, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Playa', 1701, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Primero de Mayo', 1702, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudadela Comfandi', 1703, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad Universitaria', 1705, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Buenos Aires', 1801, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Barrio Caldas', 1802, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Chorros', 1803, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Meléndez', 1804, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Farallones', 1805, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Francisco Eladio Ramirez', 1807, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Prados del Sur', 1808, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Horizontes', 1809, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Mario Correa Rengifo', 1810, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Lourdes', 1811, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Colinas del Sur', 1812, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alférez Real', 1813, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Nápoles', 1814, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Jordán', 1815, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Cuarteles Napoles', 1816, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Refugio', 1901, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Cascada', 1902, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Lido', 1903, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Tequendama', 1904, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Barrio Eucarístico', 1905, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Fernando Nuevo', 1906, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Nueva Granada', 1907, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Isabel', 1908, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Bellavista', 1909, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'San Fernando Viejo', 1910, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Miraflores', 1911, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, '3 de Julio', 1912, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Cedro', 1913, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Champagñat', 1914, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Colseguros', 1915, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Cambulos', 1916, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Mortiñal', 1917, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Militar', 1918, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Cuarto de Legua - Guadalupe', 1919, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Nueva Tequendama ', 1921, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Camino Real - Joaquín Borrero Sinisterra', 1922, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Camino Real - Los Fundadores', 1923, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Cortijo', 2001, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Belisario Caicedo', 2002, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Siloé', 2003, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Lleras Camargo', 2004, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Belén', 2005, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Brisas de Mayo', 2006, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Tierra Blanca', 2007, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Pueblo Joven', 2008, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Pízamos I', 2101, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Pízamos II', 2102, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Calimio Desepaz', 2103, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Remanso', 2104, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Líderes', 2105, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Desepaz Invicali', 2106, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Compartir', 2107, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad Talanga', 2108, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización Ciudad Jardín', 2201, 22);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Patio Bonito', 196, 1);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Aguacatal', 199, 1);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización La Merced', 293, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Vipasa', 294, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Urbanización La Flora', 295, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Altos de Menga', 296, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Area en desarrollo - Parque del Amor', 298, 2);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Alianza', 497, 4);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Parques - Barranquilla', 594, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villa del Sol', 595, 5);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Alto Nápoles ', 1898, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Santa Barbara', 1982, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Unidad Residencial El Coliseo', 1985, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'U.D. Alberto Galindo -  Plaza de Toros', 1999, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Villamercedes I - Villa Luz - Las Garzas', 2194, 21);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Asprosocial-Diamante', 1399, 13);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Naranjos I', 1496, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Promociones Populares B', 1498, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Los Naranjos II', 1499, 14);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad Cordoba', 1596, 15);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Área desocupada', 1696, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad 2000', 1697, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Alborada', 1698, 16);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad Capri', 1783, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'La Hacienda', 1784, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'El Gran Limonar', 1790, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Unicentro Cali', 1791, 17);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Alto de Los Chorros', 1890, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Polvorines', 1891, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Alto Jordán', 1897, 18);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Altos de Santa Isabel -  La Morelia', 1981, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Tejares - Cristales', 1983, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Unidad Residencial Santiago de Cali', 1984, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Cañaveralejo - Seguros Patria', 1988, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Pampa Linda', 1994, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Sector Cañaveralejo Guadalupe Antigua', 1995, 19);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Carabineros', 2097, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Venezuela - Urbanización Cañaveralejo', 2098, 20);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Ciudad Campestre', 2298, 22);
INSERT INTO APP_ASIG_NUM_TEL.GEOGRAPHIC_AREA (AREA_ID, NAME, CODE, COMMUNE)
  VALUES (SEQ_GEOGRAPHIC_AREA.NEXTVAL, 'Club Campestre', 2299, 22);
COMMIT;
