export enum Paths {
  Login = "",
  Undefined = "**",
  Centers = "centers",
  CentersByArea = "centers/area",
  RegisterCenter = "centers/register",
  CenterDetails = "centers/detail",
  UpdateCenter = "centers/update",
  Customers = "customers",
  RegisterCustomer = "customers/register",
  UploadCustomers = "customers/upload",
  CustomerDetails = "customers/detail",
  UpdateCustomer = "customers/update",
  TelephoneNumbers = "telephone-numbers",
  TelephoneNumberDetails = "telephone-numbers/detail",
  TelephoneNumberTrackingProcess = "telephone-numbers/tracking-process",
  TimeSetting = "time-setting",
}
